/*
 Navicat Premium Data Transfer

 Source Server         : PostgresSQL
 Source Server Type    : PostgreSQL
 Source Server Version : 160000 (160000)
 Source Host           : localhost:5432
 Source Catalog        : hw_week10_rakamin
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160000 (160000)
 File Encoding         : 65001

 Date: 21/10/2023 17:56:22
*/


-- ----------------------------
-- Table structure for movies
-- ----------------------------
DROP TABLE IF EXISTS "movies";
CREATE TABLE "movies" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "title" varchar(150) COLLATE "pg_catalog"."default",
  "genres" varchar(50) COLLATE "pg_catalog"."default",
  "year" varchar(50) COLLATE "pg_catalog"."default",
  "photo" "char"
)
;

-- ----------------------------
-- Records of movies
-- ----------------------------
BEGIN;
INSERT INTO "movies" ("id", "title", "genres", "year", "photo") VALUES (1, 'Reckless', 'Comedy|Drama|Romance', '2001', NULL), (2, 'When a Man Loves a Woman', 'Drama|Romance', '1995', NULL), (3, 'Creature', 'Documentary', '1997', NULL), (4, 'Sex and Zen (Rou pu Tuan zhi tou Qing bao Jian)', 'Action|Adventure|Comedy|Fantasy', '2007', NULL), (5, 'Des roses en hiver', 'Drama', '2007', NULL), (6, 'The Magical Legend of the Leprechauns', 'Adventure|Children|Comedy|Fantasy|Romance', '2010', NULL), (7, 'Marilena de la P7', 'Drama|Fantasy', '1984', NULL), (8, 'Battle of Algiers, The (La battaglia di Algeri)', 'Drama|War', '2012', NULL), (9, 'Winning of Barbara Worth, The', 'Drama|Romance|Western', '2009', NULL), (10, 'Beijing Taxi', 'Documentary', '1993', NULL), (11, 'Pleasure at Her Majesty''s', 'Comedy|Documentary', '2009', NULL), (12, 'Gang Related', 'Crime', '1993', NULL), (13, 'Bird of Paradise', 'Adventure|Drama|Romance', '1990', NULL), (14, 'Man Behind the Gun, The', 'Western', '1993', NULL), (15, 'William S. Burroughs: A Man Within', 'Documentary', '1995', NULL), (16, 'Half a Loaf of Kung Fu (Dian zhi gong fu gan chian chan)', 'Action|Comedy', '2006', NULL), (17, 'Otaku', 'Documentary', '2004', NULL), (18, 'Repeaters ', 'Action|Drama', '2009', NULL), (19, 'Party Monster', 'Documentary', '2007', NULL), (20, 'Two Days, One Night (Deux jours, une nuit)', 'Drama', '2009', NULL), (21, 'To Be or Not to Be', 'Comedy|Drama|War', '2011', NULL), (22, 'Good Student, The (Mr. Gibb)', 'Comedy', '1986', NULL), (23, 'Synth Britannia', 'Documentary', '1995', NULL), (24, 'Skenbart: En film om tåg', 'Comedy', '1993', NULL), (25, 'The Improv: 50 Years Behind the Brick Wall', 'Comedy|Documentary', '2007', NULL), (26, 'Naan Kadavul', 'Action|Drama|Mystery', '2011', NULL), (27, 'Fitzcarraldo', 'Adventure|Drama', '2004', NULL), (28, 'Liam', 'Drama', '2010', NULL), (29, 'You, Me and Dupree', 'Comedy', '2012', NULL), (30, 'Monkey Business', 'Comedy', '2012', NULL), (31, 'Run Sister Run!', 'Drama', '2006', NULL), (32, 'Police Story (Ging chaat goo si)', 'Action|Comedy|Crime|Thriller', '1991', NULL), (33, 'Come Drink with Me (Da zui xia)', 'Action|Adventure|Crime', '2006', NULL), (34, 'Libre échange', 'Comedy', '2009', NULL), (35, 'Little Monsters', 'Comedy', '2005', NULL), (36, 'Hunter, The', 'Action|Thriller', '2009', NULL), (37, 'Bite the Bullet', 'Action|Adventure|Western', '1994', NULL), (38, 'Praying with Lior', 'Documentary', '2008', NULL), (39, 'State Fair', 'Comedy|Drama|Romance', '1997', NULL), (40, 'Ursul', 'Comedy|Drama', '1996', NULL), (41, 'In Fear', 'Thriller', '2000', NULL), (42, 'Hamlet', 'Drama', '2009', NULL), (43, 'Lights Out', 'Drama|Mystery|Thriller', '2001', NULL), (44, 'Tommy', 'Drama|Musical', '2001', NULL), (45, '61*', 'Drama', '2010', NULL), (46, 'Black Sunday (La maschera del demonio)', 'Horror', '2003', NULL), (47, 'Run Sister Run!', 'Drama', '2003', NULL), (48, 'Atomic States of America, The', 'Documentary', '1992', NULL), (49, '2046', 'Drama|Fantasy|Romance|Sci-Fi', '2006', NULL), (50, 'Piano in a Factory, The (Gang de qin)', 'Comedy|Drama|Musical', '2005', NULL), (51, 'Marc Maron: Thinky Pain', 'Comedy', '1995', NULL), (52, 'Year Zero: The Silent Death of Cambodia', 'Documentary', '2005', NULL), (53, 'Valley of the Bees (Údolí vcel)', 'Drama', '1994', NULL), (54, 'Spider-Man 2', 'Action|Adventure|Sci-Fi|IMAX', '2006', NULL), (55, 'Sin Retorno', 'Drama|Thriller', '2005', NULL), (56, 'Harder They Fall, The', 'Drama|Film-Noir', '1990', NULL), (57, 'Ingrid', 'Drama', '1994', NULL), (58, 'While You Were Sleeping', 'Comedy|Romance', '1990', NULL), (59, 'Experimenter', 'Drama', '1992', NULL), (60, 'Or (a.k.a. My Treasure)', 'Drama', '1997', NULL), (61, 'Perfume', 'Comedy|Drama', '1989', NULL), (62, 'Wonder Boys', 'Comedy|Drama', '1998', NULL), (63, 'Young Törless, The (Junge Törless, Der)', 'Drama', '1983', NULL), (64, 'Conversation Piece (Gruppo di famiglia in un interno)', 'Drama', '2010', NULL), (65, 'Clean and Sober', 'Drama', '2004', NULL), (66, 'Michael Jackson''s This Is It', 'Documentary|Musical|IMAX', '1999', NULL), (67, 'Napoleon and Samantha', 'Adventure|Drama', '2000', NULL), (68, 'Last Real Men, The (Die letzten Männer)', 'Documentary', '2003', NULL), (69, 'B. Monkey', 'Crime|Romance|Thriller', '2000', NULL), (70, 'Everything or Nothing: The Untold Story of 007', 'Documentary', '2009', NULL), (71, 'Operation Crossbow', 'Action|Adventure|War', '2004', NULL), (72, 'Tere Naam', 'Romance', '2003', NULL), (73, 'Jay And Silent Bob''s Super Groovy Cartoon Movie', '(no genres listed)', '1989', NULL), (74, 'Sex and Zen (Rou pu Tuan zhi tou Qing bao Jian)', 'Action|Adventure|Comedy|Fantasy', '2009', NULL), (75, 'Korso', 'Drama', '2007', NULL), (76, 'Booty Call', 'Comedy|Romance', '2007', NULL), (77, 'In the Mirror of Maya Deren (Im Spiegel der Maya Deren)', 'Documentary', '2012', NULL), (78, 'Maid to Order', 'Comedy|Fantasy', '1995', NULL), (79, 'Alice (Neco z Alenky)', 'Animation|Fantasy|Mystery', '2011', NULL), (80, 'Zotz!', 'Comedy|Fantasy|Horror', '2007', NULL), (81, 'Hero (Ying xiong)', 'Action|Adventure|Drama', '2012', NULL), (82, 'Bed & Board (Domicile conjugal)', 'Comedy|Drama', '1999', NULL), (83, 'Nature of the Beast, The', 'Crime|Horror|Mystery|Thriller', '1986', NULL), (84, 'Odgrobadogroba', 'Comedy|Drama', '1997', NULL), (85, 'Teen Spirit', 'Comedy', '2006', NULL), (86, 'Ghost of Frankenstein, The', 'Horror', '2013', NULL), (87, 'Wadjda', 'Drama', '2002', NULL), (88, 'Blackout', 'Action|Thriller', '1996', NULL), (89, 'Secret of Moonacre, The', 'Adventure|Fantasy|Romance', '2008', NULL), (90, 'Mean Guns', 'Action|Crime|Thriller', '1986', NULL), (91, 'Pillow Talk', 'Comedy|Musical|Romance', '1999', NULL), (92, 'Fur: An Imaginary Portrait of Diane Arbus', 'Drama|Fantasy|Romance', '2010', NULL), (93, 'Lonely Guy, The', 'Comedy', '2008', NULL), (94, 'Heavy Metal', 'Action|Adventure|Animation|Horror|Sci-Fi', '2007', NULL), (95, 'Bride Wars', 'Comedy|Romance', '1989', NULL), (96, 'In Your Hands', 'Drama', '2002', NULL), (97, 'Lucky Jordan', 'Comedy|Crime|Drama', '2012', NULL), (98, 'Mostly Martha (Bella Martha)', 'Comedy|Drama|Romance', '2002', NULL), (99, 'Quebrando o Tabu', 'Documentary', '2011', NULL);
COMMIT;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "users";
CREATE TABLE "users" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "email" varchar(50) COLLATE "pg_catalog"."default",
  "gender" varchar(50) COLLATE "pg_catalog"."default",
  "password" varchar(50) COLLATE "pg_catalog"."default",
  "role" varchar(50) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of users
-- ----------------------------
BEGIN;
INSERT INTO "users" ("id", "email", "gender", "password", "role") VALUES (1, 'oainger0@craigslist.org', 'Female', 'KcAk6Mrg7DRM', 'Construction Worker'), (2, 'hblything1@de.vu', 'Female', 'QLXkU4wnRVbh', 'Engineer'), (3, 'sivermee2@vkontakte.ru', 'Male', 'cQQ0flW', 'Architect'), (4, 'agreenan3@barnesandnoble.com', 'Female', 'fk3GyIGQm', 'Electrician'), (5, 'sthirst4@blog.com', 'Male', 'rRbsjJGFMq57', 'Construction Foreman'), (6, 'loak5@nifty.com', 'Female', '46sy8hp1eJ', 'Estimator'), (7, 'ebroadey6@guardian.co.uk', 'Male', 'YkEXnE', 'Subcontractor'), (8, 'dtoupe7@surveymonkey.com', 'Female', 'QvhyaX', 'Engineer'), (9, 'jborsnall8@mediafire.com', 'Male', 'rFEoyMIhq3mF', 'Surveyor'), (10, 'cbogace9@jigsy.com', 'Male', 'nePyrtWqBf', 'Construction Worker'), (11, 'ibradnecka@clickbank.net', 'Female', 'LSXxJK', 'Estimator'), (12, 'dwoodrooffeb@purevolume.com', 'Female', 'IdyhrRQZ718W', 'Supervisor'), (13, 'amooresc@wikispaces.com', 'Female', 'RDrCEPDuJ', 'Engineer'), (14, 'kknightd@deliciousdays.com', 'Male', 'zKKphzIdn', 'Engineer'), (15, 'bharrisse@delicious.com', 'Male', 'RSWYsH240nj', 'Construction Foreman'), (16, 'jdruryf@unc.edu', 'Male', 'djBYiXGePym', 'Architect'), (17, 'drevang@yellowpages.com', 'Male', 'pU0vIZ5HeZa', 'Construction Manager'), (18, 'cbaldockh@typepad.com', 'Male', 'wf8GZ2zHkK', 'Construction Foreman'), (19, 'hdobrowskii@usnews.com', 'Male', 'ylquO3oCuD', 'Electrician'), (20, 'lwalewskij@domainmarket.com', 'Genderfluid', 'PoSJTqDJkJu', 'Surveyor'), (21, 'ovanyatink@hugedomains.com', 'Female', 'HWg7m2l3p', 'Construction Worker'), (22, 'emacbethl@tripod.com', 'Female', 'DW1WhUg416', 'Subcontractor'), (23, 'isiemonm@washingtonpost.com', 'Male', 'RcN8UVPG', 'Electrician'), (24, 'rforgann@linkedin.com', 'Male', 'qanYYdN', 'Construction Expeditor'), (25, 'vaggiso@usgs.gov', 'Male', '101IqYhQEu', 'Architect'), (26, 'mstowtep@ezinearticles.com', 'Female', 'wzrJ5FOS', 'Supervisor'), (27, 'bgrieveq@ycombinator.com', 'Female', 'Wl7DxU', 'Electrician'), (28, 'mcluneyr@instagram.com', 'Female', 'XfqCxSx', 'Electrician'), (29, 'scamplings@people.com.cn', 'Male', 'HPA7rBeO5z4z', 'Subcontractor'), (30, 'sflavellet@msn.com', 'Female', 'XcqMCe8l08', 'Estimator'), (31, 'rtrassu@wiley.com', 'Male', 'cjpwrYt', 'Engineer'), (32, 'eogelbev@youtu.be', 'Female', 'quXBIavRSi', 'Project Manager'), (33, 'vwhittenburyw@weather.com', 'Female', '2TkaD2B', 'Engineer'), (34, 'jcoakleyx@booking.com', 'Female', '8npHDaZeC', 'Construction Manager'), (35, 'cdysarty@gov.uk', 'Female', 'vcYRsxv0', 'Project Manager'), (36, 'kyeelesz@ted.com', 'Male', 'mfCgAgQSQ', 'Engineer'), (37, 'gdallinder10@wikipedia.org', 'Male', 'dlC0FP6ye', 'Subcontractor'), (38, 'jchaim11@tmall.com', 'Male', 's2o6Wn889U', 'Architect'), (39, 'mczapla12@mysql.com', 'Male', 'CMzhg3mf', 'Estimator'), (40, 'jmiddle13@sohu.com', 'Male', 'uYomHw1T', 'Construction Manager'), (41, 'mjodrelle14@reddit.com', 'Genderqueer', 'TjvO7Lu', 'Electrician'), (42, 'nvanetti15@hubpages.com', 'Female', 'JCndXgKlpOVz', 'Construction Foreman'), (43, 'porbell16@mit.edu', 'Female', 'D8iv4d7u', 'Engineer'), (44, 'ggabbatiss17@sun.com', 'Female', 'VLahPUeY', 'Electrician'), (45, 'asterricks18@cdbaby.com', 'Female', 'u9IYZr', 'Construction Foreman'), (46, 'skibbee19@hatena.ne.jp', 'Male', '6hhuUZI', 'Construction Foreman'), (47, 'mgullick1a@google.com.br', 'Male', '5Um7pk', 'Subcontractor'), (48, 'hpebworth1b@flickr.com', 'Male', 'zLY23wqE', 'Estimator'), (49, 'ematterface1c@hud.gov', 'Female', 'IqXMqHX1dqZI', 'Construction Manager'), (50, 'bmacneilage1d@photobucket.com', 'Female', 'jOn56QwXu0', 'Construction Manager'), (51, 'scharlo1e@columbia.edu', 'Male', 'XwOXpF2o', 'Estimator'), (52, 'egeelan1f@reverbnation.com', 'Male', 'eo8o49n', 'Construction Worker'), (53, 'tnegro1g@businessinsider.com', 'Female', 'msbmE7VYO', 'Construction Foreman'), (54, 'abarette1h@economist.com', 'Male', 'pJhz9oD', 'Construction Worker'), (55, 'gwarrier1i@alexa.com', 'Male', 'vALnpHEe5Ls', 'Electrician'), (56, 'lridge1j@mit.edu', 'Male', 'CxQ0xKCeusmx', 'Construction Manager'), (57, 'bwelldrake1k@lulu.com', 'Male', 'TUpIGkydUS5', 'Construction Manager'), (58, 'fmoncey1l@is.gd', 'Male', 'caxRTR', 'Surveyor'), (59, 'codogherty1m@cnn.com', 'Female', 'uaxexy7K', 'Construction Foreman'), (60, 'aflaubert1n@lycos.com', 'Male', 'BLobMX49FfOe', 'Construction Expeditor'), (61, 'grattery1o@unblog.fr', 'Bigender', 'R0vX8qB', 'Subcontractor'), (62, 'nmcelory1p@purevolume.com', 'Agender', '0rodhPg', 'Architect'), (63, 'bmattiassi1q@discovery.com', 'Female', 'cgIWWaui6Eto', 'Electrician'), (64, 'jjenking1r@lycos.com', 'Female', 'RKQ0YcsD0Q', 'Estimator'), (65, 'rsartain1s@diigo.com', 'Male', 'BnVh8nIPoFz', 'Estimator'), (66, 'eandreas1t@bing.com', 'Male', '02xcGrtP', 'Construction Worker'), (67, 'elilleman1u@nhs.uk', 'Male', 'M069bmTA', 'Construction Foreman'), (68, 'jbachs1v@tumblr.com', 'Male', '0dhxcWTlqI', 'Project Manager'), (69, 'sslayton1w@webeden.co.uk', 'Genderfluid', 'fSoZFZ1f', 'Construction Foreman'), (70, 'rwilby1x@stumbleupon.com', 'Male', '1Eis0oPLtZa', 'Construction Worker'), (71, 'aspreckley1y@eventbrite.com', 'Male', '9UwgSi', 'Construction Foreman'), (72, 'cgorghetto1z@amazon.com', 'Male', '9iunBFGj', 'Project Manager'), (73, 'ctreuge20@geocities.jp', 'Male', 'RfRfdUe', 'Construction Foreman'), (74, 'bsavage21@about.com', 'Female', 'OpUmD57qr3', 'Project Manager'), (75, 'nfrift22@bizjournals.com', 'Female', 'OuoSRXNL02q', 'Subcontractor'), (76, 'lbranton23@nature.com', 'Non-binary', 'tp8Nh6Q', 'Architect'), (77, 'dworvill24@utexas.edu', 'Female', 'wqgonO', 'Construction Worker'), (78, 'bbilling25@shop-pro.jp', 'Male', 'deh5cBZ', 'Engineer'), (79, 'tdelahaye26@statcounter.com', 'Female', 'wIsr5g', 'Engineer'), (80, 'jseath27@cornell.edu', 'Male', 'kq81gRLpMOKJ', 'Construction Expeditor'), (81, 'votoole28@friendfeed.com', 'Polygender', 'eui66Ct23z', 'Project Manager'), (82, 'kcortez29@hao123.com', 'Male', 'IW9jHyFWHC', 'Electrician'), (83, 'coldford2a@scientificamerican.com', 'Male', 'pkZ8BZ58', 'Surveyor'), (84, 'kdoorbar2b@si.edu', 'Female', '0t024J', 'Engineer'), (85, 'dmizen2c@berkeley.edu', 'Female', 'f1KdDMMjS', 'Project Manager'), (86, 'waldred2d@thetimes.co.uk', 'Female', 'yVNQzjaQ', 'Subcontractor'), (87, 'nclulee2e@cloudflare.com', 'Female', 'RbqPLdCAgn', 'Architect'), (88, 'rdanielsson2f@opera.com', 'Male', 'faECcaM', 'Electrician'), (89, 'ehailwood2g@shareasale.com', 'Non-binary', 'onZHOEmlLc', 'Architect'), (90, 'aanyon2h@shareasale.com', 'Male', 'QfmF0xdT', 'Construction Worker'), (91, 'rvasic2i@ihg.com', 'Male', 'gTLp0Woas', 'Electrician'), (92, 'rzarb2j@pcworld.com', 'Male', 'C1ZmRFsrG2', 'Subcontractor'), (93, 'tvennart2k@google.it', 'Male', 'xYYRAKf1eFk', 'Subcontractor'), (94, 'nstuther2l@google.it', 'Female', 'aSpkH8', 'Surveyor'), (95, 'hlotterington2m@ed.gov', 'Female', 'HLur8P0', 'Project Manager'), (96, 'gkeys2n@netvibes.com', 'Female', 'AvGmAuf1b', 'Estimator'), (97, 'tspedding2o@sciencedirect.com', 'Female', 'gceCxisIrK1P', 'Construction Foreman'), (98, 'cborrill2p@sciencedirect.com', 'Male', 'L38dNYJaR6F', 'Project Manager'), (99, 'ceard2q@china.com.cn', 'Female', '6zZaAQONzaDl', 'Supervisor'), (100, 'sduligall2r@washington.edu', 'Male', '6VHZvc2E', 'Engineer');
COMMIT;

-- ----------------------------
-- Auto increment value for movies
-- ----------------------------
SELECT setval('"movies_id_seq"', 1, true);

-- ----------------------------
-- Primary Key structure for table movies
-- ----------------------------
ALTER TABLE "movies" ADD CONSTRAINT "movies_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for users
-- ----------------------------
SELECT setval('"users_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
